AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  InstanceType:
    Type: String
  AMI:
    Type: String
  KeyPair:
    Type: String
  SubnetId:
    Type: String
  SecurityGroup:
    Type: String
  AssignPublicIp:
    Type: String
    AllowedValues: ['true', 'false']
    Description: Create a public instance and assign eip if this parameter is set to 'true'
  
Conditions:
  PublicEC2: !Equals [ !Ref AssignPublicIp, 'true']

Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMI
      KeyName: !Ref KeyPair
      NetworkInterfaces:
        - AssociatePublicIpAddress: !Ref AssignPublicIp
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !If [PublicEC2, 'BastionInstance', 'PrivateInstance']
  EC2EIP:
    Condition: PublicEC2
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref EC2