Parameters:
  VpcId:
    Type: String
  PublicSubnet1:
    Type: String

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcId
      InternetGatewayId: !Ref InternetGateway

  EIP:
    Type: AWS::EC2::EIP    

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP.AllocationId   
      SubnetId: !Ref PublicSubnet1
