Resources:
  DhVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
      Parameters:
        VPCCIDR: !Ref VPCCIDR

  SubnetConfiguration:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: subnets.yaml
      Parameters:
        VpcId: !GetAtt DhVPC.Outputs.VPCId
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR

  InternetConfiguration:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: internet.yaml
      Parameters:
        VpcId: !GetAtt DhVPC.Outputs.VPCId
        PublicSubnet1: !GetAtt SubnetConfiguration.Outputs.PublicSubnet1
