AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcId:
    Type: String
  MyFWIP:
    Type: String
  MyIP:
    Type: String


Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EC2 instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - SourceSecurityGroupId: !GetAtt BastionSecurityGroup.GroupId
          IpProtocol: -1
      Tags:
        - Key: Name
          Value: Private-EC2

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Bastion Host
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - CidrIp: !Ref MyIP
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - CidrIp: !Ref MyFWIP
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
      Tags:
        - Key: Name
          Value: Bastion-EC2

Outputs:
  BastionSG:
    Value: !Ref BastionSecurityGroup
  PrivateEC2SG:
    Value: !Ref EC2SecurityGroup