AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcId:
    Type: String


Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EC2 instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - SourceSecurityGroupId: !GetAtt BastionSecurityGroup.GroupId
          IpProtocol: -1

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Bastion Host
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22

Outputs:
  BastionSG:
    Value: !Ref BastionSecurityGroup
  PrivateEC2SG:
    Value: !Ref EC2SecurityGroup