AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VPCCIDR:
    Type: String

Resources:
  DhVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref DhVPC
      InternetGatewayId: !Ref InternetGateway

Outputs:
  VPCId:
    Value: !Ref DhVPC
  IGWId:
    Value: !Ref InternetGateway
